* Copyright

Advanced Simulation Library (ASL) [[http://asl.org.il]]

Copyright 2015 Avtech Scientific [[http://avtechscientific.com]]

ASL is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, version 3 of the License.

ASL is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with ASL. If not, see [[http://www.gnu.org/licenses/]].

All files, and specifically the images in =doc/Developer-Guide/pics= are part of the ASL project and are covered by its license except where stated otherwise (=cmake/Modules=).

** Optional commercial license

Optional [[http://asl.org.il/licensing][commercial license]] is available for closed-source ventures wishing to make a financial contribution to the development of ASL.

** Author attributions

If ASL is used for research that will be published or otherwise publicly distributed, we kindly ask that this fact is mentioned.

The reference to ASL may be in an acknowledgment section, in a phrase such as the following:

#+BEGIN_EXAMPLE
    "This work benefited from the use of the Advanced Simulation Library™ (ASL),
     an open source hardware accelerated multiphysics simulation platform developed
     by Avtech Scientific and available at <http://asl.org.il>."
#+END_EXAMPLE

To cite ASL in publications please adopt the following:

/ASL: Advanced Simulation Library™, an open source hardware accelerated multiphysics simulation platform/.[fn:1] Version 0.1.5.[fn:2] 2015-08-01.[fn:3] [[http://asl.org.il]].[fn:4] Avtech Scientific. Modiin Illit, Israel.

[fn:1] Additionally any sub-routines that were used may be specified.
[fn:2] Version number or commit hash (in the latter case write: Commit 794e4916).
[fn:3] Release or commit date.
[fn:4] The URL should be an active hyperlink wherever technically possible.
