option(BUILD_SHARED_LIBS "Build shared libraries" ON)
option(WITH_EXAMPLES "Build with examples" ON)
option(WITH_MATIO "Build with Matlab support" OFF)
option(WITH_API_DOC "Compile doxygen API documentation" OFF)
option(WITH_TESTS "Build with tests" ON)